# Generated by Django 5.0.3 on 2024-05-12 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dyMall', '0006_produk_toko'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produk',
            name='toko',
        ),
    ]
